# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yean/faculdade/ifmove

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yean/faculdade/ifmove

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yean/faculdade/ifmove/CMakeFiles /home/yean/faculdade/ifmove//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yean/faculdade/ifmove/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ifmove

# Build rule for target.
ifmove: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ifmove
.PHONY : ifmove

# fast build rule for target.
ifmove/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/build
.PHONY : ifmove/fast

#=============================================================================
# Target rules for targets named window_test

# Build rule for target.
window_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 window_test
.PHONY : window_test

# fast build rule for target.
window_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/window_test.dir/build.make CMakeFiles/window_test.dir/build
.PHONY : window_test/fast

#=============================================================================
# Target rules for targets named acceleration_test

# Build rule for target.
acceleration_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acceleration_test
.PHONY : acceleration_test

# fast build rule for target.
acceleration_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acceleration_test.dir/build.make CMakeFiles/acceleration_test.dir/build
.PHONY : acceleration_test/fast

#=============================================================================
# Target rules for targets named matrix_test

# Build rule for target.
matrix_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrix_test
.PHONY : matrix_test

# fast build rule for target.
matrix_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_test.dir/build.make CMakeFiles/matrix_test.dir/build
.PHONY : matrix_test/fast

#=============================================================================
# Target rules for targets named particle_test

# Build rule for target.
particle_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 particle_test
.PHONY : particle_test

# fast build rule for target.
particle_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particle_test.dir/build.make CMakeFiles/particle_test.dir/build
.PHONY : particle_test/fast

#=============================================================================
# Target rules for targets named vector3_test

# Build rule for target.
vector3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vector3_test
.PHONY : vector3_test

# fast build rule for target.
vector3_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vector3_test.dir/build.make CMakeFiles/vector3_test.dir/build
.PHONY : vector3_test/fast

#=============================================================================
# Target rules for targets named game_test

# Build rule for target.
game_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_test
.PHONY : game_test

# fast build rule for target.
game_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_test.dir/build.make CMakeFiles/game_test.dir/build
.PHONY : game_test/fast

#=============================================================================
# Target rules for targets named MultipleCircleCollision

# Build rule for target.
MultipleCircleCollision: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MultipleCircleCollision
.PHONY : MultipleCircleCollision

# fast build rule for target.
MultipleCircleCollision/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleCircleCollision.dir/build.make CMakeFiles/MultipleCircleCollision.dir/build
.PHONY : MultipleCircleCollision/fast

src/MultiCircleCollision.o: src/MultiCircleCollision.cpp.o
.PHONY : src/MultiCircleCollision.o

# target to build an object file
src/MultiCircleCollision.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/MultiCircleCollision.cpp.o
.PHONY : src/MultiCircleCollision.cpp.o

src/MultiCircleCollision.i: src/MultiCircleCollision.cpp.i
.PHONY : src/MultiCircleCollision.i

# target to preprocess a source file
src/MultiCircleCollision.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/MultiCircleCollision.cpp.i
.PHONY : src/MultiCircleCollision.cpp.i

src/MultiCircleCollision.s: src/MultiCircleCollision.cpp.s
.PHONY : src/MultiCircleCollision.s

# target to generate assembly for a file
src/MultiCircleCollision.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/MultiCircleCollision.cpp.s
.PHONY : src/MultiCircleCollision.cpp.s

src/arrow2.o: src/arrow2.cpp.o
.PHONY : src/arrow2.o

# target to build an object file
src/arrow2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/arrow2.cpp.o
.PHONY : src/arrow2.cpp.o

src/arrow2.i: src/arrow2.cpp.i
.PHONY : src/arrow2.i

# target to preprocess a source file
src/arrow2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/arrow2.cpp.i
.PHONY : src/arrow2.cpp.i

src/arrow2.s: src/arrow2.cpp.s
.PHONY : src/arrow2.s

# target to generate assembly for a file
src/arrow2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/arrow2.cpp.s
.PHONY : src/arrow2.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/gcircle.o: src/gcircle.cpp.o
.PHONY : src/gcircle.o

# target to build an object file
src/gcircle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gcircle.cpp.o
.PHONY : src/gcircle.cpp.o

src/gcircle.i: src/gcircle.cpp.i
.PHONY : src/gcircle.i

# target to preprocess a source file
src/gcircle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gcircle.cpp.i
.PHONY : src/gcircle.cpp.i

src/gcircle.s: src/gcircle.cpp.s
.PHONY : src/gcircle.s

# target to generate assembly for a file
src/gcircle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gcircle.cpp.s
.PHONY : src/gcircle.cpp.s

src/gmesh2.o: src/gmesh2.cpp.o
.PHONY : src/gmesh2.o

# target to build an object file
src/gmesh2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gmesh2.cpp.o
.PHONY : src/gmesh2.cpp.o

src/gmesh2.i: src/gmesh2.cpp.i
.PHONY : src/gmesh2.i

# target to preprocess a source file
src/gmesh2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gmesh2.cpp.i
.PHONY : src/gmesh2.cpp.i

src/gmesh2.s: src/gmesh2.cpp.s
.PHONY : src/gmesh2.s

# target to generate assembly for a file
src/gmesh2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gmesh2.cpp.s
.PHONY : src/gmesh2.cpp.s

src/gparticle.o: src/gparticle.cpp.o
.PHONY : src/gparticle.o

# target to build an object file
src/gparticle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gparticle.cpp.o
.PHONY : src/gparticle.cpp.o

src/gparticle.i: src/gparticle.cpp.i
.PHONY : src/gparticle.i

# target to preprocess a source file
src/gparticle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gparticle.cpp.i
.PHONY : src/gparticle.cpp.i

src/gparticle.s: src/gparticle.cpp.s
.PHONY : src/gparticle.s

# target to generate assembly for a file
src/gparticle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gparticle.cpp.s
.PHONY : src/gparticle.cpp.s

src/graphics.o: src/graphics.cpp.o
.PHONY : src/graphics.o

# target to build an object file
src/graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/graphics.cpp.o
.PHONY : src/graphics.cpp.o

src/graphics.i: src/graphics.cpp.i
.PHONY : src/graphics.i

# target to preprocess a source file
src/graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/graphics.cpp.i
.PHONY : src/graphics.cpp.i

src/graphics.s: src/graphics.cpp.s
.PHONY : src/graphics.s

# target to generate assembly for a file
src/graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/graphics.cpp.s
.PHONY : src/graphics.cpp.s

src/grid.o: src/grid.cpp.o
.PHONY : src/grid.o

# target to build an object file
src/grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/grid.cpp.o
.PHONY : src/grid.cpp.o

src/grid.i: src/grid.cpp.i
.PHONY : src/grid.i

# target to preprocess a source file
src/grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/grid.cpp.i
.PHONY : src/grid.cpp.i

src/grid.s: src/grid.cpp.s
.PHONY : src/grid.s

# target to generate assembly for a file
src/grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/grid.cpp.s
.PHONY : src/grid.cpp.s

src/gsquare.o: src/gsquare.cpp.o
.PHONY : src/gsquare.o

# target to build an object file
src/gsquare.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gsquare.cpp.o
.PHONY : src/gsquare.cpp.o

src/gsquare.i: src/gsquare.cpp.i
.PHONY : src/gsquare.i

# target to preprocess a source file
src/gsquare.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gsquare.cpp.i
.PHONY : src/gsquare.cpp.i

src/gsquare.s: src/gsquare.cpp.s
.PHONY : src/gsquare.s

# target to generate assembly for a file
src/gsquare.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gsquare.cpp.s
.PHONY : src/gsquare.cpp.s

src/gtriangle.o: src/gtriangle.cpp.o
.PHONY : src/gtriangle.o

# target to build an object file
src/gtriangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gtriangle.cpp.o
.PHONY : src/gtriangle.cpp.o

src/gtriangle.i: src/gtriangle.cpp.i
.PHONY : src/gtriangle.i

# target to preprocess a source file
src/gtriangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gtriangle.cpp.i
.PHONY : src/gtriangle.cpp.i

src/gtriangle.s: src/gtriangle.cpp.s
.PHONY : src/gtriangle.s

# target to generate assembly for a file
src/gtriangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/gtriangle.cpp.s
.PHONY : src/gtriangle.cpp.s

src/mesh2.o: src/mesh2.cpp.o
.PHONY : src/mesh2.o

# target to build an object file
src/mesh2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/mesh2.cpp.o
.PHONY : src/mesh2.cpp.o

src/mesh2.i: src/mesh2.cpp.i
.PHONY : src/mesh2.i

# target to preprocess a source file
src/mesh2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/mesh2.cpp.i
.PHONY : src/mesh2.cpp.i

src/mesh2.s: src/mesh2.cpp.s
.PHONY : src/mesh2.s

# target to generate assembly for a file
src/mesh2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/mesh2.cpp.s
.PHONY : src/mesh2.cpp.s

src/mesh2_utils.o: src/mesh2_utils.cpp.o
.PHONY : src/mesh2_utils.o

# target to build an object file
src/mesh2_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/mesh2_utils.cpp.o
.PHONY : src/mesh2_utils.cpp.o

src/mesh2_utils.i: src/mesh2_utils.cpp.i
.PHONY : src/mesh2_utils.i

# target to preprocess a source file
src/mesh2_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/mesh2_utils.cpp.i
.PHONY : src/mesh2_utils.cpp.i

src/mesh2_utils.s: src/mesh2_utils.cpp.s
.PHONY : src/mesh2_utils.s

# target to generate assembly for a file
src/mesh2_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/mesh2_utils.cpp.s
.PHONY : src/mesh2_utils.cpp.s

src/particle.o: src/particle.cpp.o
.PHONY : src/particle.o

# target to build an object file
src/particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/particle.cpp.o
.PHONY : src/particle.cpp.o

src/particle.i: src/particle.cpp.i
.PHONY : src/particle.i

# target to preprocess a source file
src/particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/particle.cpp.i
.PHONY : src/particle.cpp.i

src/particle.s: src/particle.cpp.s
.PHONY : src/particle.s

# target to generate assembly for a file
src/particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/particle.cpp.s
.PHONY : src/particle.cpp.s

src/point2.o: src/point2.cpp.o
.PHONY : src/point2.o

# target to build an object file
src/point2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/point2.cpp.o
.PHONY : src/point2.cpp.o

src/point2.i: src/point2.cpp.i
.PHONY : src/point2.i

# target to preprocess a source file
src/point2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/point2.cpp.i
.PHONY : src/point2.cpp.i

src/point2.s: src/point2.cpp.s
.PHONY : src/point2.s

# target to generate assembly for a file
src/point2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/point2.cpp.s
.PHONY : src/point2.cpp.s

src/sdl.o: src/sdl.cpp.o
.PHONY : src/sdl.o

# target to build an object file
src/sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/sdl.cpp.o
.PHONY : src/sdl.cpp.o

src/sdl.i: src/sdl.cpp.i
.PHONY : src/sdl.i

# target to preprocess a source file
src/sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/sdl.cpp.i
.PHONY : src/sdl.cpp.i

src/sdl.s: src/sdl.cpp.s
.PHONY : src/sdl.s

# target to generate assembly for a file
src/sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/sdl.cpp.s
.PHONY : src/sdl.cpp.s

src/shape.o: src/shape.cpp.o
.PHONY : src/shape.o

# target to build an object file
src/shape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/shape.cpp.o
.PHONY : src/shape.cpp.o

src/shape.i: src/shape.cpp.i
.PHONY : src/shape.i

# target to preprocess a source file
src/shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/shape.cpp.i
.PHONY : src/shape.cpp.i

src/shape.s: src/shape.cpp.s
.PHONY : src/shape.s

# target to generate assembly for a file
src/shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/shape.cpp.s
.PHONY : src/shape.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ifmove.dir/build.make CMakeFiles/ifmove.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

tests/MultipleCircleCollision_test.o: tests/MultipleCircleCollision_test.cpp.o
.PHONY : tests/MultipleCircleCollision_test.o

# target to build an object file
tests/MultipleCircleCollision_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleCircleCollision.dir/build.make CMakeFiles/MultipleCircleCollision.dir/tests/MultipleCircleCollision_test.cpp.o
.PHONY : tests/MultipleCircleCollision_test.cpp.o

tests/MultipleCircleCollision_test.i: tests/MultipleCircleCollision_test.cpp.i
.PHONY : tests/MultipleCircleCollision_test.i

# target to preprocess a source file
tests/MultipleCircleCollision_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleCircleCollision.dir/build.make CMakeFiles/MultipleCircleCollision.dir/tests/MultipleCircleCollision_test.cpp.i
.PHONY : tests/MultipleCircleCollision_test.cpp.i

tests/MultipleCircleCollision_test.s: tests/MultipleCircleCollision_test.cpp.s
.PHONY : tests/MultipleCircleCollision_test.s

# target to generate assembly for a file
tests/MultipleCircleCollision_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleCircleCollision.dir/build.make CMakeFiles/MultipleCircleCollision.dir/tests/MultipleCircleCollision_test.cpp.s
.PHONY : tests/MultipleCircleCollision_test.cpp.s

tests/acceleration_test.o: tests/acceleration_test.cpp.o
.PHONY : tests/acceleration_test.o

# target to build an object file
tests/acceleration_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acceleration_test.dir/build.make CMakeFiles/acceleration_test.dir/tests/acceleration_test.cpp.o
.PHONY : tests/acceleration_test.cpp.o

tests/acceleration_test.i: tests/acceleration_test.cpp.i
.PHONY : tests/acceleration_test.i

# target to preprocess a source file
tests/acceleration_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acceleration_test.dir/build.make CMakeFiles/acceleration_test.dir/tests/acceleration_test.cpp.i
.PHONY : tests/acceleration_test.cpp.i

tests/acceleration_test.s: tests/acceleration_test.cpp.s
.PHONY : tests/acceleration_test.s

# target to generate assembly for a file
tests/acceleration_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acceleration_test.dir/build.make CMakeFiles/acceleration_test.dir/tests/acceleration_test.cpp.s
.PHONY : tests/acceleration_test.cpp.s

tests/game_test.o: tests/game_test.cpp.o
.PHONY : tests/game_test.o

# target to build an object file
tests/game_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_test.dir/build.make CMakeFiles/game_test.dir/tests/game_test.cpp.o
.PHONY : tests/game_test.cpp.o

tests/game_test.i: tests/game_test.cpp.i
.PHONY : tests/game_test.i

# target to preprocess a source file
tests/game_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_test.dir/build.make CMakeFiles/game_test.dir/tests/game_test.cpp.i
.PHONY : tests/game_test.cpp.i

tests/game_test.s: tests/game_test.cpp.s
.PHONY : tests/game_test.s

# target to generate assembly for a file
tests/game_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_test.dir/build.make CMakeFiles/game_test.dir/tests/game_test.cpp.s
.PHONY : tests/game_test.cpp.s

tests/matrix_test.o: tests/matrix_test.cpp.o
.PHONY : tests/matrix_test.o

# target to build an object file
tests/matrix_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_test.dir/build.make CMakeFiles/matrix_test.dir/tests/matrix_test.cpp.o
.PHONY : tests/matrix_test.cpp.o

tests/matrix_test.i: tests/matrix_test.cpp.i
.PHONY : tests/matrix_test.i

# target to preprocess a source file
tests/matrix_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_test.dir/build.make CMakeFiles/matrix_test.dir/tests/matrix_test.cpp.i
.PHONY : tests/matrix_test.cpp.i

tests/matrix_test.s: tests/matrix_test.cpp.s
.PHONY : tests/matrix_test.s

# target to generate assembly for a file
tests/matrix_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_test.dir/build.make CMakeFiles/matrix_test.dir/tests/matrix_test.cpp.s
.PHONY : tests/matrix_test.cpp.s

tests/particle_test.o: tests/particle_test.cpp.o
.PHONY : tests/particle_test.o

# target to build an object file
tests/particle_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particle_test.dir/build.make CMakeFiles/particle_test.dir/tests/particle_test.cpp.o
.PHONY : tests/particle_test.cpp.o

tests/particle_test.i: tests/particle_test.cpp.i
.PHONY : tests/particle_test.i

# target to preprocess a source file
tests/particle_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particle_test.dir/build.make CMakeFiles/particle_test.dir/tests/particle_test.cpp.i
.PHONY : tests/particle_test.cpp.i

tests/particle_test.s: tests/particle_test.cpp.s
.PHONY : tests/particle_test.s

# target to generate assembly for a file
tests/particle_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particle_test.dir/build.make CMakeFiles/particle_test.dir/tests/particle_test.cpp.s
.PHONY : tests/particle_test.cpp.s

tests/vector3_test.o: tests/vector3_test.cpp.o
.PHONY : tests/vector3_test.o

# target to build an object file
tests/vector3_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vector3_test.dir/build.make CMakeFiles/vector3_test.dir/tests/vector3_test.cpp.o
.PHONY : tests/vector3_test.cpp.o

tests/vector3_test.i: tests/vector3_test.cpp.i
.PHONY : tests/vector3_test.i

# target to preprocess a source file
tests/vector3_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vector3_test.dir/build.make CMakeFiles/vector3_test.dir/tests/vector3_test.cpp.i
.PHONY : tests/vector3_test.cpp.i

tests/vector3_test.s: tests/vector3_test.cpp.s
.PHONY : tests/vector3_test.s

# target to generate assembly for a file
tests/vector3_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vector3_test.dir/build.make CMakeFiles/vector3_test.dir/tests/vector3_test.cpp.s
.PHONY : tests/vector3_test.cpp.s

tests/window_test.o: tests/window_test.cpp.o
.PHONY : tests/window_test.o

# target to build an object file
tests/window_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/window_test.dir/build.make CMakeFiles/window_test.dir/tests/window_test.cpp.o
.PHONY : tests/window_test.cpp.o

tests/window_test.i: tests/window_test.cpp.i
.PHONY : tests/window_test.i

# target to preprocess a source file
tests/window_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/window_test.dir/build.make CMakeFiles/window_test.dir/tests/window_test.cpp.i
.PHONY : tests/window_test.cpp.i

tests/window_test.s: tests/window_test.cpp.s
.PHONY : tests/window_test.s

# target to generate assembly for a file
tests/window_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/window_test.dir/build.make CMakeFiles/window_test.dir/tests/window_test.cpp.s
.PHONY : tests/window_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MultipleCircleCollision"
	@echo "... acceleration_test"
	@echo "... game_test"
	@echo "... ifmove"
	@echo "... matrix_test"
	@echo "... particle_test"
	@echo "... vector3_test"
	@echo "... window_test"
	@echo "... src/MultiCircleCollision.o"
	@echo "... src/MultiCircleCollision.i"
	@echo "... src/MultiCircleCollision.s"
	@echo "... src/arrow2.o"
	@echo "... src/arrow2.i"
	@echo "... src/arrow2.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/gcircle.o"
	@echo "... src/gcircle.i"
	@echo "... src/gcircle.s"
	@echo "... src/gmesh2.o"
	@echo "... src/gmesh2.i"
	@echo "... src/gmesh2.s"
	@echo "... src/gparticle.o"
	@echo "... src/gparticle.i"
	@echo "... src/gparticle.s"
	@echo "... src/graphics.o"
	@echo "... src/graphics.i"
	@echo "... src/graphics.s"
	@echo "... src/grid.o"
	@echo "... src/grid.i"
	@echo "... src/grid.s"
	@echo "... src/gsquare.o"
	@echo "... src/gsquare.i"
	@echo "... src/gsquare.s"
	@echo "... src/gtriangle.o"
	@echo "... src/gtriangle.i"
	@echo "... src/gtriangle.s"
	@echo "... src/mesh2.o"
	@echo "... src/mesh2.i"
	@echo "... src/mesh2.s"
	@echo "... src/mesh2_utils.o"
	@echo "... src/mesh2_utils.i"
	@echo "... src/mesh2_utils.s"
	@echo "... src/particle.o"
	@echo "... src/particle.i"
	@echo "... src/particle.s"
	@echo "... src/point2.o"
	@echo "... src/point2.i"
	@echo "... src/point2.s"
	@echo "... src/sdl.o"
	@echo "... src/sdl.i"
	@echo "... src/sdl.s"
	@echo "... src/shape.o"
	@echo "... src/shape.i"
	@echo "... src/shape.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
	@echo "... tests/MultipleCircleCollision_test.o"
	@echo "... tests/MultipleCircleCollision_test.i"
	@echo "... tests/MultipleCircleCollision_test.s"
	@echo "... tests/acceleration_test.o"
	@echo "... tests/acceleration_test.i"
	@echo "... tests/acceleration_test.s"
	@echo "... tests/game_test.o"
	@echo "... tests/game_test.i"
	@echo "... tests/game_test.s"
	@echo "... tests/matrix_test.o"
	@echo "... tests/matrix_test.i"
	@echo "... tests/matrix_test.s"
	@echo "... tests/particle_test.o"
	@echo "... tests/particle_test.i"
	@echo "... tests/particle_test.s"
	@echo "... tests/vector3_test.o"
	@echo "... tests/vector3_test.i"
	@echo "... tests/vector3_test.s"
	@echo "... tests/window_test.o"
	@echo "... tests/window_test.i"
	@echo "... tests/window_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

